backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),  # noqa E501
]

backend/crm/urls.py
from django.urls import path

from backend.crm import views as v

app_name = 'crm'


urlpatterns = [
    path('', v.ClienteListView.as_view(), name='cliente_list'),  # noqa E501
    path('create/', v.ClienteCreateView.as_view(), name='cliente_create'),  # noqa E501
    path('<int:pk>/', v.ClienteDetailView.as_view(), name='cliente_detail'),  # noqa E501
    path('<int:pk>/update/', v.ClienteUpdateView.as_view(), name='cliente_update'),  # noqa E501
    # path('<int:pk>/delete/', v.ClienteDeleteView.as_view(), name='cliente_delete'),  # noqa E501
]

backend/servico/urls.py
from django.urls import path

from backend.servico import views as v

app_name = 'servico'


urlpatterns = [
    path('', v.ordem_servico_list, name='ordem_servico_list'),  # noqa E501
    path('create/', v.ordem_servico_create, name='ordem_servico_create'),  # noqa E501
    path('<int:pk>/', v.ordem_servico_detail, name='ordem_servico_detail'),  # noqa E501
    path('<int:pk>/update/', v.ordem_servico_update, name='ordem_servico_update'),  # noqa E501
    # path('<int:pk>/delete/', v.ordem_servico_delete, name='ordem_servico_delete'),  # noqa E501
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from ninja import NinjaAPI

from .api import api

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('crm/', include('backend.crm.urls', namespace='crm')),
    path('servico/', include('backend.servico.urls', namespace='servico')),
    path('admin/', admin.site.urls),
    path("api/v1/", api.urls),
]

backend/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class Endereco(models.Model):
    endereco = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    complemento = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    bairro = models.CharField(
        'bairro',
        max_length=100,
        null=True,
        blank=True
    )
    cidade = models.CharField('cidade', max_length=100, null=True, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True

backend/crm/models.py
from django.db import models
from django.urls import reverse_lazy

from backend.core.models import Endereco


class Cliente(Endereco):
    razao_social = models.CharField('Razão Social', max_length=120, unique=True)
    cnpj = models.CharField('CNPJ', max_length=14, null=True, blank=True)

    class Meta:
        ordering = ('razao_social',)
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return f'{self.razao_social}'

    def get_absolute_url(self):
        return reverse_lazy('crm:cliente_detail', kwargs={'pk': self.pk})

backend/servico/models.py
from django.db import models

from backend.crm.models import Cliente


class Servico(models.Model):
    titulo = models.CharField('Título', max_length=100)

    class Meta:
        ordering = ('titulo',)
        verbose_name = 'serviço'
        verbose_name_plural = 'serviços'

    def __str__(self):
        return f'{self.titulo}'


SITUACAO = (
    ('pe', 'Pendente'),
    ('ca', 'Cancelado'),
    ('an', 'Andamento'),
    ('ap', 'Aprovado'),
)


class OrdemServico(models.Model):
    situacao = models.CharField('Situação', max_length=2, choices=SITUACAO)
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,
        verbose_name='cliente',
        related_name='ordem_servicos',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'ordem de serviço'
        verbose_name_plural = 'ordens de serviço'

    def __str__(self):
        return f'{self.pk}'


class OrdemServicoItem(models.Model):
    ordem_servico = models.ForeignKey(
        OrdemServico,
        on_delete=models.CASCADE,
        verbose_name='ordem de serviço',
        related_name='ordem_servico_itens',
    )
    servico = models.ForeignKey(
        Servico,
        on_delete=models.CASCADE,
        verbose_name='serviço',
        related_name='ordem_servico_item_servicos',
    )
    valor = models.DecimalField('valor', max_digits=8, decimal_places=2, null=True, blank=True)
    proxima_visita = models.DateField('Próxima Visita', null=True, blank=True)

    class Meta:
        ordering = ('-pk',)  # ordem decrescente, se quiser crescente só tirar o sinal de menos.
        verbose_name = 'item da ordem de serviço'
        verbose_name_plural = 'itens da ordens de serviço'

    def __str__(self):
        return f'{self.pk}'

backend/crm/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):
    cnpj = forms.CharField(max_length=18, label='CNPJ')

    class Meta:
        model = Cliente
        fields = ('razao_social', 'cnpj', 'endereco', 'complemento', 'bairro', 'cidade', 'uf', 'cep')

backend/servico/forms.py
from django import forms

from .models import OrdemServico


class OrdemServicoForm(forms.ModelForm):
    servico = forms.CharField()
    valor = forms.DecimalField()
    proxima_visita = forms.DateField(
        label='Próxima Visita',
        required=False,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'form-control'
            }),
        input_formats=('%Y-%m-%d',),
    )

    class Meta:
        model = OrdemServico
        fields = ('situacao',)

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/crm/views.py
from django.db.models import Q
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from .forms import ClienteForm
from .models import Cliente


class ClienteListView(ListView):
    model = Cliente
    paginate_by = 20

    def get_queryset(self):
        qs = self.model.objects.all()
        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(
                Q(razao_social__icontains=search)
                | Q(bairro__icontains=search)
                | Q(cidade__icontains=search)
            )
        return qs


class ClienteDetailView(DetailView):
    model = Cliente


class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm


class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteForm


# class ClienteDeleteView(DeleteView):
#     model = Cliente
#     success_url = reverse_lazy('crm:cliente_list')

backend/servico/views.py
from django.shortcuts import render

from .forms import OrdemServicoForm
from .models import OrdemServico


def ordem_servico_list(request):
    template_name = 'servico/ordem_servico_list.html'
    object_list = OrdemServico.objects.all()

    search = request.GET.get('search')
    if search:
        object_list = object_list.filter(situacao=search)

    context = {'object_list': object_list}
    return render(request, template_name, context)


def ordem_servico_create(request):
    template_name = 'servico/ordem_servico_form.html'
    context = {'form': OrdemServicoForm}
    return render(request, template_name, context)


def ordem_servico_detail(request, pk):
    template_name = 'servico/ordem_servico_detail.html'
    instance = OrdemServico.objects.get(pk=pk)
    context = {'object': instance}
    return render(request, template_name, context)


def ordem_servico_update(request, pk):
    ...


def ordem_servico_delete(request, pk):
    ...

backend/core/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <link rel="shortcut icon" href="https://alpinejs.dev/favicon.png">
    <title>Serviço</title>

  <!-- Bootstrap core CSS -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">


  <!-- Font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Alpine Plugins -->
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script>

  <!-- Alpine Core -->
    <script defer src="//unpkg.com/alpinejs" defer></script>

    {% block css %}{% endblock css %}

  </head>

  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% include "includes/menu.html" %}

          {% block content %}{% endblock content %}
        </div>
      </div>
    </div>

    {% block js %}{% endblock js %}
  </body>

</html>

backend/core/templates/includes/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#bs-example-navbar-collapse-1"
  >
    <span class="navbar-toggler-icon"></span>
  </button> <a
    class="navbar-brand"
    href="{% url 'core:index' %}"
  >Home</a>
  <div
    class="collapse navbar-collapse"
    id="bs-example-navbar-collapse-1"
  >
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a
          class="nav-link"
          href="{% url 'crm:cliente_list' %}"
        >Clientes <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="#"
        >Serviços</a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{% url 'servico:ordem_servico_list' %}"
        >Ordens de Serviço</a>
      </li>
    </ul>
  </div>
</nav>

backend/core/templates/includes/pagination.html
<!-- pagination.html -->
<div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3">
  <nav class="w-full sm:w-auto sm:mr-auto">
    <ul class="pagination">

      <!-- Início da paginação -->

      <!-- Primeira página -->
      {% if page_obj.number != 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-left" class="lucide lucide-chevrons-left w-4 h-4" data-lucide="chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg> </a>
        </li>
      {% endif %}

      <!-- Página anterior -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-left" class="lucide lucide-chevron-left w-4 h-4" data-lucide="chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg> </a>
        </li>
      {% endif %}

      <!-- ... -->
      <!-- {% if page_obj.number != 1 %}
        <li class="page-item"> <a class="page-link" href="#">...</a> </li>
      {% endif %} -->

      <!-- Páginas do meio -->
      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 2 primeiras e 2 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' %}

          <li class="page-item {% if page_obj.number == pg %}active{% endif %}"> <a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a> </li>

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
            <!-- Mostra 2 páginas antes e 2 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"> <a class="page-link" href="#">...</a> </li>
          {% endif %}

        {% endif %}
      {% endfor %}

      <!-- ... -->
      <!-- {% if page_obj.number != page_obj.paginator.num_pages %}
        <li class="page-item"> <a class="page-link" href="#">...</a> </li>
      {% endif %} -->

      <!-- Próxima página -->
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-right" class="lucide lucide-chevron-right w-4 h-4" data-lucide="chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg> </a>
        </li>
      {% endif %}

      <!-- Última página -->
      {% if page_obj.number != page_obj.paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-right" class="lucide lucide-chevrons-right w-4 h-4" data-lucide="chevrons-right"><polyline points="13 17 18 12 13 7"></polyline><polyline points="6 17 11 12 6 7"></polyline></svg> </a>
        </li>
      {% endif %}
      <!-- Fim da paginação -->

    </ul>
  </nav>
</div>

backend/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h2>
      Sistema de Ordens de Serviço
    </h2>
    <p>
      Gerencie suas Ordens de Serviço com facilidade.
    </p>
    <p>
      <a
        class="btn btn-primary btn-large"
        href="#"
      >Criar Ordem de Serviço</a>
    </p>
  </div>
{% endblock content %}

backend/crm/templates/crm/cliente_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes do Cliente: {{ object.razao_social }}</h1>

  <a
    href="{% url 'crm:cliente_list' %}"
    class="btn btn-link mb-3"
  >Voltar</a>
  <a
    href="{% url 'crm:cliente_create' %}"
    class="btn btn-primary mb-3"
  >Adicionar</a>

  <div class="row">
    <div class="col-md-12">
      <div class="list-group">
        <a
          href="#"
          class="list-group-item list-group-item-action flex-column align-items-start"
        >
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Razão Social</h5>
          <!-- <small class="text-muted">3 days ago</small> -->
          </div>
          <p class="mb-1">{{ object.razao_social }}</p>
          <small class="text-muted">{{ object.cnpj }}</small>
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

backend/crm/templates/crm/cliente_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
  <div x-data>
    <h1>Adicionar Cliente</h1>

    <div class="row">
      <div class="cols">
        <form
          action="."
          method="POST"
        >
          {% csrf_token %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.label }}">{{ field.label }}</label>
              {% render_field field class="form-control" %}

              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="text-danger">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}

          <button
            type="submit"
            class="btn btn-primary"
          >Salvar</button>

        </form>
      </div>
    </div>
  </div>
{% endblock content %}

backend/crm/templates/crm/cliente_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Lista de Clientes</h1>

  <a
    href="{% url 'crm:cliente_create' %}"
    class="btn btn-primary"
  >Adicionar</a>

  <form id="searchForm">
    <input
      id="id_search"
      name="search"
      class="form-control"
      type="text"
      placeholder="Busca..."
      autofocus
    />
  </form>

  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Razão Social</th>
            <th>CNPJ</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
                <a href="{{ object.get_absolute_url }}">{{ object.razao_social }}</a>
              </td>
              <td>{{ object.cnpj }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include "includes/pagination.html" %}
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script>
// Get the input field and form
    var input = document.getElementById("id_search");
    var form = document.getElementById("searchForm");

// Add event listener for keypress
    input.addEventListener("keypress", function(event) {
      if (event.keyCode === 13) {
        event.preventDefault(); // Prevent form submission via Enter key
        form.submit(); // Submit the form
      }
    });
  </script>
{% endblock js %}

backend/servico/templates/servico/ordem_servico_detail.html
<!-- ordem_servico_detail.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes da OS {{ object }} - {{ object.cliente }}</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Serviço</th>
        <th>Valor</th>
        <th>Próxima Visita</th>
      </tr>
    </thead>
    <tbody>
      {% for item in object.ordem_servico_itens.all %}
        <tr>
          <td>{{ item.servico }}</td>
          <td>{{ item.valor }}</td>
          <td>{{ item.proxima_visita|date:"d/m/Y" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

backend/servico/templates/servico/ordem_servico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
  <link
    rel="stylesheet"
    href="{% static 'css/autocomplete.css' %}"
  >
{% endblock css %}

{% block content %}
  <div x-data="getData">
    <h1>Adicionar Ordem de Serviço</h1>
    <h2></h2>

    <form @submit.prevent="saveData">

    <!-- busca cliente -->
      <div class="form-group row autocomplete">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Cliente</label>
        <div class="col-sm-10">
        <!-- manual -->
          <input
            type="text"
            class="form-control"
            placeholder="Cliente"
            x-model="searchCliente"
          >
          <ul
            id="id_ul"
            x-show="clienteShow"
          >
            <template
              x-for="cliente in clientes"
              :key="cliente.id"
            >
              <li
                x-text="cliente.razao_social"
                @click="getCliente(cliente)"
              ></li>
            </template>
          </ul>
        </div>
      <!-- <p x-text="searchCliente"></p> -->
      </div>

    <!-- resultado cliente -->
    <!-- <ul class="list-group">
      <template
        x-for="cliente in clientes"
        :key="cliente.id"
      >
        <li
          class="list-group-item"
          x-text="cliente.razao_social"
          @click="getCliente(cliente)"
        ></li>
      </template>
    </ul> -->

    <!-- <p x-text="clienteSelecionado.id"></p> -->

      <div class="form-group row">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Situação</label>
        <div class="col-sm-10">
        <!-- widget_tweaks -->
          {% render_field form.situacao class="form-control" x-model="ordemServico.situacao" %}
        </div>
      </div>

      <p>Endereço: <span x-text="clienteSelecionado.endereco"></span></p>
      <p>Bairro: <span x-text="clienteSelecionado.bairro"></span></p>

    <!-- busca servico -->
      <div class="form-group row autocomplete">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Serviço</label>
        <div class="col-sm-10">
        <!-- manual -->
          <input
            type="text"
            class="form-control"
            placeholder="servico"
            x-model="searchServico"
          >
          <ul
            id="id_ul"
            x-show="servicoShow"
          >
            <template
              x-for="servico in servicos"
              :key="servico.id"
            >
              <li
                x-text="servico.titulo"
                @click="getServico(servico)"
              ></li>
            </template>
          </ul>
        </div>
        <p x-text="searchServico"></p>
      </div>

    <!-- <p x-text="servicoSelecionado.id"></p> -->

      <div class="form-group row">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Valor</label>
        <div class="col-sm-10">
          {% render_field form.valor class="form-control" min="0" step="0.01" x-model="ordemServicoItem.valor" %}
        </div>
      </div>

      <div class="form-group row">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Próxima Visita</label>
        <div class="col-sm-10">
          {% render_field form.proxima_visita class="form-control" x-model="ordemServicoItem.proximaVisita" %}
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-10">
          <button
            type="button"
            class="btn btn-primary"
            @click="addItem"
          >Adicionar</button>
          <button
            type="submit"
            class="btn btn-success"
          >Salvar</button>
        </div>
      </div>

    </form>

    <table class="table">
      <thead>
        <tr>
          <th>Descrição (Serviço)</th>
          <th>Valor</th>
          <th>Próx. Visita</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <template
          x-for="item in ordemServicoItems"
          :key="item.id"
        >
          <tr>
            <td x-text="item.servico_titulo"></td>
            <td x-text="item.valor"></td>
            <td x-text="item.proxima_visita"></td>
            <td
              class="text-primary"
              @click="deleteOrdemServicoItem(item.id)"
            >Deletar</td>
          </tr>
        </template>
      </tbody>
    </table>
  </div>
{% endblock content %}

{% block js %}
  <script
    src="{% static 'js/servico/servico.js' %}"
    data-csrf="{{ csrf_token }}"
  ></script>
{% endblock js %}

backend/servico/templates/servico/ordem_servico_list.html
<!-- ordem_servico_list.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Ordens de Serviço</h1>

  <a
    href="{% url 'servico:ordem_servico_create' %}"
    class="btn btn-primary"
  >Adicionar</a>

  <div class="row mt-3">
    <div class="col-sm-2">
      <h3>Situação</h3>
      <div class="list-group">
        <a
          href="{% url 'servico:ordem_servico_list' %}"
          class="list-group-item list-group-item-action"
        >
          Limpar filtro
        </a>
        <a
          href="{% url 'servico:ordem_servico_list' %}?search=pe"
          class="list-group-item list-group-item-action"
        >
          Pendente
        </a>
        <a
          href="{% url 'servico:ordem_servico_list' %}?search=ca"
          class="list-group-item list-group-item-action"
        >
          Cancelado
        </a>
        <a
          href="{% url 'servico:ordem_servico_list' %}?search=an"
          class="list-group-item list-group-item-action"
        >
          Andamento
        </a>
        <a
          href="{% url 'servico:ordem_servico_list' %}?search=ap"
          class="list-group-item list-group-item-action"
        >
          Aprovado
        </a>
      </div>

    </div>
    <div class="col-sm-10">
      <table class="table">
        <thead>
          <tr>
            <th>Num</th>
            <th>Cliente</th>
            <th>Situação</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.pk }}</td>
              <td>
                <a href="{% url 'servico:ordem_servico_detail' object.pk %}">{{ object.cliente }}</a>
              </td>
              <td>{{ object.get_situacao_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}